### ISSUE TITLE
Avoid tampering with gfx gamma

### ISSUE THREAD

**Issue by ElenaXX** [JeffMcClintock/SynthEdit-Tracking#18]
SE should really stop altering/playing with gfx gamma. I.e a png with a 50% transparent white must be rendered as such on its background, and the same is true for vector graphics. Otherwise, things done in an external gfx program will look differently in SE and/or in the exported plugin. This disobeys the WYSIWYG rule, also implies a lot of pow() or however tabulated computations which just increase CPU load unnecessarily other than having a detrimental effect. SE should NOT alter the gamma.

**Comment by JeffMcClintock** [comment]
SynthEdit uses a linear colorspace.
SynthEdits rendering is not necessarily inconsistent with that of professional graphics software.

Below is an example from Affinity Designer. The top half is rendered in Affinity, the bottom half in SynthEdit.
Each section shows a solid white square above a solid black square. Over the top at the left are 50% transparent black squares and at the right 50% transparent white squares.

The resulting colors in SynthEdit are very close to those of Affinity. You can also see that "50% black over white" give a consistent result with "50% white over black".

Some software uses by default a sRGB colourspace and will give different results.

The reason we prefer to use a linear colorspace is enable transparency effects such as shadows and glows to have a more natural and lifelike appearance.

Some more information on the advantages of correct color blending:
https://dev.rbcafe.com/unity/unity-5.3.3/en/Manual/LinearLighting.html

![image](https://github.com/user-attachments/assets/a9e61b3c-d126-44b1-8244-9acad6b60c0b)

**Comment by Sasha-Radojevic** [comment]
OMG, JEFF!!!

CAN YOU PLEASE JUST DROP THAT ARGUMENT AND LISTEN TO THE USERS!!!

NOBODY CARES ABOUT THE CORRECT COLOR BLENDING!!!

WE WANT PNG AND SVG GRAPHICS RENDERED CORRECTLLY!!!

Stop finding edge cases/excuses that nobody will ever use and commit to the standard.

**Comment by ElenaXX** [comment]
Nope. He really dismisses this topic. He is not going to change his mind. I will investigate if those sdk functions can be replaced with a custom png loader then.

**Comment by ElenaXX** [comment]
I keep insisting  forever that such a strange and nonstandard behaviour is not wanted by users, so trashing every complaint and request to change it is not appropriate, considering that we paid for Synth Edit.
If you have a png image (or vector graphics) constituted by a solid white box with an alpha channel gradient, it shall forcibly look as a fading *white* over the underlying graphics, i.e when alpha is 0.5 a pixel shall result (r+1)/2, (g+1)/2, (b+1)/2, where r,g,b is the color of an underlying pixel. Not instead, you made it look as (r+0.5)/2, (g+0.5)/2, (b+0.5)/2, i.e as though the solid white were replaced by the same alpha channel. This is a *wrong way of doing gfx operations* other than something nobody ever asked for, and we warned you since a long time. You should attain to the established standards for gfx composition without altering gamma, alpha and color spaces in *no way and for no reason*

**Comment by Sasha-Radojevic** [comment]
No discussion, just obey! Hashtag IGNORMENT. lol

I have a suggestion that would satisfy both you Jeff and us, non-Jeffs. Give us the option to choose between the two methods. You keep using the correct way of mixing colors and brag about it on nerd conventions and everyone else will choose the correct display of graphics and forget about your stupid mistake. We all make them, allow yourself admitting this one.
