### ISSUE TITLE
Hover Function in Build 542 and up Breaks Set and Release Capture Functionality

### ISSUE THREAD

**Issue by MarkSynth** [JeffMcClintock/SynthEdit-Tracking#25]
@JeffMcClintock 
Description:
Since the introduction of the sethover function and changes in build 542 and up, the set and release capture functionality has been compromised. Previously, it was possible to create a hover module that allowed users to click and hold the left mouse button to change a knob’s value while moving the cursor over another hover module. This setup enabled seamless interaction across multiple modules.

However, in the current builds, when the mouse moves from one hover module to another while the left button is held down, the data connection is immediately broken, making it impossible to maintain continuous control over the knob value. This issue disrupts workflows that rely on interacting with multiple hover modules simultaneously.

Expected Behavior:

The set and release capture functionality should allow users to click and hold the left mouse button on a hover module and continue to change a knob’s value even when the mouse moves over another hover module.
The data connection should remain active and intact until the mouse button is released, regardless of crossing between different hover modules.

Current Behavior in Build 542 and up:

Moving the mouse from one hover module to another while holding down the left mouse button immediately breaks the data connection, preventing continuous value adjustment.

Steps to Reproduce:

Set up two hover modules in SynthEdit with a knob connected to one of them.
Click and hold the left mouse button on the first hover module to adjust the knob's value.
Move the mouse over the second hover module while still holding the button.

Impact:
This issue severely impacts the functionality of hover modules, making it difficult to implement complex user interactions that involve multiple hover zones. The broken data connection disrupts workflows and limits the versatility of the hover function.

Tag: bug

**Comment by JeffMcClintock** [comment]
fix in SynthEdit 1.5 Build 562: when a module has captured the mouse, the 'hover' functionality is now restricted to only that module.
