### ISSUE TITLE
Unable to launch SE 1.5 b562

### ISSUE THREAD

**Issue by ovm-plugin** [JeffMcClintock/SynthEdit-Tracking#34]
Once installed, SE 1.5 start but don't show up, asking 1st to bring a modification to the computer, then fail to authorize (Cubase) Retrologue synth... 
In the task manager it either doesn't appear or it's considered as a background application, then when it gets on top it's associated with (Cubase) Retrologue. Cubase E-licenser is up-to-date. SE 1.4 asked that authorization 2 month ago but started anyway.
- SE 1.4 runs ok.
- SE 1.5 started with admin rights obviously

**Comment by JeffMcClintock** [comment]
thanks @ovm-plugin , can you clarify: SynthEdit is presenting a message box about Retrologue? (which is a VST3 plugin).

Do you have the SynthEdit VST3 Wrapper? Is that what is giving an error? (when it is scanning Retrologue)?

**Comment by ovm-plugin** [comment]
Hi Jeff
Here is the message 
![retrologue_license](https://github.com/user-attachments/assets/1bab6bd4-9b42-4820-970f-96a8f3b6e5ff)
Here in the task manager
![task_manager_SE1 5](https://github.com/user-attachments/assets/189a7c0f-e80a-4ccb-91ea-bc11c5c2f995)
Also, after installing 1.5 I can't use the pop-up recent file menu in the task bar to open SE 1.4, otherwise it doesn't show neither, still hidden in the task manager...
If I 1st open it, then use the internal SE recent file open menu, it works.

**Comment by ovm-plugin** [comment]
Hi Jeff,
No news here, still the same problem.

> Do you have the SynthEdit VST3 Wrapper?

What is that, I don't understand your question?

Best regards, ovm

**Comment by ovm-plugin** [comment]
Hi
I have uninstalled Cubase Vst3 host and Retrologue (!), but apparently the problem was that the firewall blocked SE 1.5..
Now it works.
Still, it's weird.

**Comment by JeffMcClintock** [comment]
This is strange, since SynthEdit itself dosn't control Retrologue (it's a Steinberg plugin).
Since it's working now I'll close this.
