### ISSUE TITLE
Wires don't follow container resizing

### ISSUE THREAD

**Issue by Sasha-Radojevic** [JeffMcClintock/SynthEdit-Tracking#36]
Hi Jeff,

Wires do not follow container resizing.

Here's the before state:
![image](https://github.com/user-attachments/assets/6f710093-a5d0-4b0b-8241-e54047b04a27)

And when container is resized:
![image](https://github.com/user-attachments/assets/81671e09-a871-4bab-bab4-814012e8ca86)

Wires appear hanging freely, not attached to the appropriate pin:
![image](https://github.com/user-attachments/assets/c2851ebd-1fc4-4bbd-80fd-0ea21f584805)

Thanks,
Sasha

**Comment by JeffMcClintock** [comment]
This is fixed in Build 563
