### ISSUE TITLE
Bug: Incorrect plugin version number displayed in DAWs despite correct version number in XML

### ISSUE THREAD

**Issue by MrPlugDev** [JeffMcClintock/SynthEdit-Tracking#42]
Description:
Plugin version numbers are displayed incorrectly in DAWs, even though the correct version number is specified in the plugin XML file. For example, if version 1.2 is specified in the factory XML, the DAW always shows version 1.0.

Steps to reproduce:

-Open the plugin XML file and set the version number (e.g., 1.2).
-Load the plugin in a DAW.
-Check the plugin version displayed in the DAW.
-Observe that the DAW displays an incorrect version number (e.g., 1.0) instead of the version specified in the XML.
Additional Information:

The discrepancy occurs consistently across different DAWs, affecting the display of version numbers.

Tag: #Bug

**Comment by JeffMcClintock** [comment]
I saved a fresh plugin, changed the version number in the file factory.se.xml (in the plugin Resources). Then loaded the plugin in Cubase 10.5, the plugin manager reported the correct version number.

<img width="440" alt="image" src="https://github.com/user-attachments/assets/53ef2398-9c2a-485b-a104-1443a8c4126b">

I then changed the Version number in a plugin that Cubase had already scanned, Cubase did not pick up the change. (You may need to delete any cache that the DAWkeeps of the plugin data).
