### ISSUE TITLE
Main container displays plugin incorrectly when set to "Controls on Module" with no skin option

### ISSUE THREAD

**Issue by MrPlugDev** [JeffMcClintock/SynthEdit-Tracking#45]
Description:
The main container always displays the plugin incorrectly when it is set to "Controls on Module" and no skin can be applied. The expected behavior is for the plugin to be displayed correctly in this mode, but the display does not match the intended design.

Steps to reproduce:

-Set the main container of a plugin to "Controls on Module"
-Observe that the plugin is not displayed correctly.
-Note that no skin option is available for adjustment.
-Compare the display to the intended design or expected behavior.

Additional Information:
The issue affects how the plugin is shown is SE when the main container is configured to show controls on module and does not allow for skin customization.

Tag: #Bug

**Comment by JeffMcClintock** [comment]
On the Structure-view, SynthEdit shows the default skin only.
This is working correctly as intended.

However we can categorise this as a feature-request.
