### ISSUE TITLE
VST3 plugin creates a preset called "Full Reset" when opened, which is undesirable behavior

### ISSUE THREAD

**Issue by MrPlugDev** [JeffMcClintock/SynthEdit-Tracking#53]
By default, a VST3 plugin creates a preset called "Full Reset" when opened in DAW, which is undesirable behavior. If a plugin is delivered commercially to a customer with a default soundbank with an arbitrary name, the plugin will create an "other" soundbank by default, with this "Full Reset" preset in it. Please Resolve.

#tag: Bug

**Comment by JeffMcClintock** [comment]
fixed. A fresh VST3 plugin will now by default load the first preset name of your project.
