### ISSUE TITLE
CPU Readout wrong on event-driven modules

### ISSUE THREAD

**Issue by JeffMcClintock** [JeffMcClintock/SynthEdit-Tracking#65]
Modules that process signals intermittently and sleep a lot e.g. MIDI modules show an unusual and inaccurate CPU readout.

<img width="88" alt="image" src="https://github.com/user-attachments/assets/eedd4f5a-001b-4970-9601-aa7706e66d49">

**Comment by DavidsonAudioMulti** [comment]
v1.5.577 - 2024-11-08

more accurate CPU readout on modules that sleep often

I think this may have effected something when I do this below debug window open, then turn on the audio engine SE crashes. This is the very outer most container. It may take 10 or more seconds to crash but it will eventually 30 sec or so. If I use inside this outer most container the debug window no issues


![image](https://github.com/user-attachments/assets/b5f5de83-3d25-4850-af31-3df46ac0025f)


Hope this helps.
