### ISSUE TITLE
URGENT: The DSP part of the last edited PM is not updated on preset change

### ISSUE THREAD

**Issue by Sasha-Radojevic** [JeffMcClintock/SynthEdit-Tracking#67]
Here is a test VST3 and the Presets:
[https://www.dropbox.com/scl/fo/zo18eu7y403nvkrugeqyp/h?rlkey=309y6a7bp1swznlhllgf67wj0&dl=0](https://github.com/JeffMcClintock/SynthEdit-Tracking/issues/url)

1. Play a note.
2. Transpose OCT to -2:
 ![image](https://github.com/user-attachments/assets/daadda4a-7478-41d4-a985-0f814507292a)
3. Play the same note to hear the change in pitch.
4. Select the next preset:
![image](https://github.com/user-attachments/assets/187ab56d-8401-4995-ae46-824b9ea9a1f9)
5. Play a note.
6. Transpose OCT to -2.
7. Play the same note.

The GUI is updated but there is no change in pitch this time. It seems that the DSP part of the last edited PM is not updated on preset change.

I'm not sure if it only affects List PM, but it's easiest to replicate the bug with it.

**Comment by Sasha-Radojevic** [comment]
If it helps, this bug does not happen with Audio Unit.

**Comment by JeffMcClintock** [comment]
thanks, fixed in SE V 1.5 built 579

**Comment by Sasha-Radojevic** [comment]
Hi Jeff,

Thanks for fixing this one, but I'm afraid that the fix introduced a bug in SE.

For the first time I'm seeing in SE that the content of the Preset List changes depending on which window is in focus.

If the **main container** is in focus, then the list looks like this:
![image](https://github.com/user-attachments/assets/1511ca15-379c-43ea-bcf0-7392ffcd4d03)

If the **plugin container** is in focus, then the list looks like this:
![image](https://github.com/user-attachments/assets/e91fd6fa-7d5b-40c0-b752-e7fc3745e79a)

Here's a [test project](https://www.dropbox.com/scl/fi/w6k1elfp2ayo7utc3oxyw/Preset-names-test.synthedit?rlkey=wjhjvy209ei1ms7ni4v161tom&dl=0).
