### ISSUE TITLE
Integer PM in Reason 13: Negative numbers in audio are offset by one in comparison to displayed value

### ISSUE THREAD

**Issue by Sasha-Radojevic** [JeffMcClintock/SynthEdit-Tracking#68]
Here's the test VST3:
[https://www.dropbox.com/scl/fo/zo18eu7y403nvkrugeqyp/h?rlkey=309y6a7bp1swznlhllgf67wj0&dl=0](https://github.com/JeffMcClintock/SynthEdit-Tracking/issues/url)

1. Select the Chord mode:
![image](https://github.com/user-attachments/assets/143c56d8-32e2-4fe7-b8df-407eb48f4f36)
2. Double-click on numbers below to reset them to Zero.
3. Play a note.
4. Change any of the numbers to "-1"
5. Play the same note. One note of the chord should be transposed -1 semitone, but it's not.
6. Change the number to "-2". Now it will sound like one semitone down.

The problem is only in Reason 13.

It works fine in Bitwig, Live, Reaper.

**Comment by JeffMcClintock** [comment]
Thanks, I found a bug relating to negative integer values.

Fixed in SE V1.5 build 583
