### ISSUE TITLE
Some Characters are Excluded from Preset Names on Plugin Export

### ISSUE THREAD

**Issue by Sasha-Radojevic** [JeffMcClintock/SynthEdit-Tracking#73]
Hi Jeff,

These characters are removed from preset names on a plugin export:
!@#$%^&()+[]{};

Also, hyphens are replaced by underscores.

Some examples of preset names in SE and how they end up exported:

- "amper&sand" --> "ampersand"
- "(brackets)" --> "brackets"
- "[brackets]" --> "brackets"
- "pl+us" --> "plus"
- "min-us" --> "min_us"

Here's a [test project](https://www.dropbox.com/scl/fi/w6k1elfp2ayo7utc3oxyw/Preset-names-test.synthedit?rlkey=wjhjvy209ei1ms7ni4v161tom&dl=0).

1. Export the plugin.
2. Look into its presets folder to compare exported filenames with preset names in SE.

**Comment by JeffMcClintock** [comment]
SynthEdit saves presets as files.

The following characters are not allowed in filenames on Windows:

< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
^ (caret)

I'll enable the other ones.

Fix in SynthEdit 1.5 Build 581
