### ISSUE TITLE
A bug fix maybe introduced a new one

### ISSUE THREAD

**Issue by Sasha-Radojevic** [JeffMcClintock/SynthEdit-Tracking#74]
Hi Jeff,

Thanks for fixing 67, but I'm afraid that the fix introduced a bug in SE.

For the first time I'm seeing in SE that the content of the Preset List changes depending on which window is in focus.

If the **main container** is in focus, then the list looks like this:
![image](https://github.com/user-attachments/assets/1511ca15-379c-43ea-bcf0-7392ffcd4d03)

If the **plugin container** is in focus, then the list looks like this:
![image](https://github.com/user-attachments/assets/e91fd6fa-7d5b-40c0-b752-e7fc3745e79a)

Here's a [test project](https://www.dropbox.com/scl/fi/w6k1elfp2ayo7utc3oxyw/Preset-names-test.synthedit?rlkey=wjhjvy209ei1ms7ni4v161tom&dl=0).

_Originally posted by @Sasha-Radojevic in https://github.com/JeffMcClintock/SynthEdit-Tracking/issues/67#issuecomment-2496093244_

**Comment by JeffMcClintock** [comment]
This is the correct behavior.
The Preset List in the tool bar at the top should reflect the current patch of the active Window.

What can be confusing is that the main container always has patches, even when there is not any patch-automator in there.

In SE V1.5 build 584 I have fixed two inconsistencies:

- The toolbar now shows blank presets as e.g. "Patch 001", which is consistent with the Preset Browser module. Previously they showed as blank entries.
- The toolbar now syncs the currently selected preset when you change it from a preset-browser. Previously it ignored that.
