### ISSUE TITLE
Copy and paste bug in SE V 1.5-586 and 587.

### ISSUE THREAD

**Issue by tubeohm** [JeffMcClintock/SynthEdit-Tracking#82]
SE Version V 1.5- 586 and 587.
Copy and paste does not work for some graphic elements.
For example, if Led 2 or a simple button is copied and pasted, the LED does not work and the button cannot be turned.

Synthfreak

**Comment by Steve4380** [comment]
if I copy a button only, then insert an LED as normal from the browser the LED/Button work as expected, however if I copy/paste the button AND LED together, the button works as expected, but the LED doesn't change state. A voltmeter connected to the button changes from 0 to 10 V as expected, but the LED is stuck. If the LED is in the "off" state when copied, it changes  to "on" as soon as its pasted. Very odd.
Could this be PatchMem related I wonder. If I can find out any more I'll add it to this report.

**Comment by JeffMcClintock** [comment]
I made a fix for this in SE V 1.5 build 588
