### ISSUE TITLE
Int to bool (GUI and DSP) act differently as Float to bool (GUI and DSP) and Volt to bool

### ISSUE THREAD

**Issue by Sylv1o** [JeffMcClintock/SynthEdit-Tracking#9]
Hi Jeff, 

It's a very small issue but it could cause real headaches...

Flaot to bool (GUI and DSP) and Volt to bool output TRUE only if input > 0 (negative value send false)

Int to bool (GUI and DSP) output TRUE if input >0 OR < 0, Negative value send TRUE !!

I can see no valid reason and it's very confusing.

Could you have a quick look ?

Thanks in advance

**Comment by Sylv1o** [comment]
Oh, I think I remember that I already report that in the past and you said that it was an error but you fear to break compatibility of projects of users if you change it now...

So don't bother with that bug...

**Comment by maxbreges** [comment]
[IntToBool.zip](https://github.com/user-attachments/files/16790067/IntToBool.zip)

**Comment by JeffMcClintock** [comment]
I'll close this since it is too late to change this behaviour without breaking peoples projects.
